#!/usr/bin/env bash

## launch rofi with alt config

#CONFIG="$HOME/.config/rofi/config"
#STYLE="$HOME/.config/rofi/style.css"
#COLORS="$HOME/.config/rofi/colors"

## launch wofi with alt config

CONFIG="$HOME/.config/wofi/config"
STYLE="$HOME/.config/wofi/style.css"
COLORS="$HOME/.config/wofi/colors"

if [[ ! `pidof wofi` ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill wofi
fi

